<?php

namespace SwaggerGen;

use Exception as BaseException;

/**
 * Exception class to differentiate exceptions generated by the SwaggerGen
 * library from those thrown from other code.
 *
 * @package    SwaggerGen
 * @author     Martijn van der Lee <martijn@vanderlee.com>
 * @copyright  2014-2025 Martijn van der Lee
 * @license    https://opensource.org/licenses/MIT MIT
 */
class Exception extends BaseException
{

}
